// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Data;

#nullable disable

namespace PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20261001094727_AddResources")]
    partial class AddResources
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Features.Resources.Models.ResourceNexus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApacheSupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("AtosAgentDeployed")
                        .HasColumnType("text");

                    b.Property<bool>("AutoShutdownEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("AutoShutdownEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("AutoShutdownSchedule")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("AutoShutdownStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("AzureMonitoringSetupRequired")
                        .HasColumnType("text");

                    b.Property<string>("AzureResourceId")
                        .HasColumnType("text");

                    b.Property<string>("BackupRequired")
                        .HasColumnType("text");

                    b.Property<string>("BackupSchedule")
                        .HasColumnType("text");

                    b.Property<string>("BackupStatus")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<string>("CronJobsTaskScheduler")
                        .HasColumnType("text");

                    b.Property<string>("DBASupport")
                        .HasColumnType("text");

                    b.Property<string>("DBASupportServiceLevel")
                        .HasColumnType("text");

                    b.Property<string>("DNS")
                        .HasColumnType("text");

                    b.Property<string>("DailyBackupTime")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseInstance")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("text");

                    b.Property<string>("Disk1OSPerformance")
                        .HasColumnType("text");

                    b.Property<string>("Disk2DataPerformance")
                        .HasColumnType("text");

                    b.Property<string>("Disk3DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk4DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk5DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk6DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disks")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentTag")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfrastructureSupportAzure")
                        .HasColumnType("text");

                    b.Property<string>("InfrastructureSupportServiceLevel")
                        .HasColumnType("text");

                    b.Property<string>("JavaSupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MonitoringHealthcheckURL")
                        .HasColumnType("text");

                    b.Property<string>("NewHostname")
                        .HasColumnType("text");

                    b.Property<string>("OSSupportIncludingPatching")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<string>("OracleDBASupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("PlanVersion")
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .HasColumnType("text");

                    b.Property<string>("PrivateIPAddress")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<string>("ProximityGroup")
                        .HasColumnType("text");

                    b.Property<string>("PublicIPAddress")
                        .HasColumnType("text");

                    b.Property<int?>("RamGB")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceGroup")
                        .HasColumnType("text");

                    b.Property<string>("ResponseSLARequirement")
                        .HasColumnType("text");

                    b.Property<string>("SMTPEnabled")
                        .HasColumnType("text");

                    b.Property<string>("SMTPHostname")
                        .HasColumnType("text");

                    b.Property<string>("SMTPSender")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subscription")
                        .HasColumnType("text");

                    b.Property<string>("ThreeDExperienceSXILicense")
                        .HasColumnType("text");

                    b.Property<string>("TomEEPortConnector")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VMCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VMDeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirtualNetworkSubnet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Resources", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
