// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Data;

#nullable disable

namespace PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Migrations
{
    [DbContext(typeof(ApplicationDatabaseContext))]
    [Migration("20261006185715_AddEnvironmentOverview")]
    partial class AddEnvironmentOverview
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Features.EnvironmentOverview.Models.EnvironmentOverviewNexus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionItemsUpdates")
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationCustomisationVersion")
                        .HasColumnType("text");

                    b.Property<string>("CurrentUptimeSchedule")
                        .HasColumnType("text");

                    b.Property<string>("DNSURL")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDecommissioned")
                        .HasColumnType("boolean");

                    b.Property<string>("Priority1")
                        .HasColumnType("text");

                    b.Property<string>("Priority2")
                        .HasColumnType("text");

                    b.Property<string>("Priority3")
                        .HasColumnType("text");

                    b.Property<string>("Purpose")
                        .HasColumnType("text");

                    b.Property<string>("Sponsor")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IG_EnvironmentOverviewTBL", (string)null);
                });

            modelBuilder.Entity("PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Features.Resources.Models.ResourceNexus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ApacheSupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("AtosAgentDeployed")
                        .HasColumnType("text");

                    b.Property<bool>("AutoShutdownEnabled")
                        .HasColumnType("boolean");

                    b.Property<TimeOnly?>("AutoShutdownEndTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("AutoShutdownSchedule")
                        .HasColumnType("text");

                    b.Property<TimeOnly?>("AutoShutdownStartTime")
                        .HasColumnType("time without time zone");

                    b.Property<string>("AzureMonitoringSetupRequired")
                        .HasColumnType("text");

                    b.Property<string>("AzureResourceId")
                        .HasColumnType("text");

                    b.Property<string>("BackupRequired")
                        .HasColumnType("text");

                    b.Property<string>("BackupSchedule")
                        .HasColumnType("text");

                    b.Property<string>("BackupStatus")
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<int?>("CpuCores")
                        .HasColumnType("integer");

                    b.Property<string>("CronJobsTaskScheduler")
                        .HasColumnType("text");

                    b.Property<string>("DBASupport")
                        .HasColumnType("text");

                    b.Property<string>("DBASupportServiceLevel")
                        .HasColumnType("text");

                    b.Property<string>("DNS")
                        .HasColumnType("text");

                    b.Property<string>("DailyBackupTime")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseInstance")
                        .HasColumnType("text");

                    b.Property<string>("DatabaseName")
                        .HasColumnType("text");

                    b.Property<string>("Disk1OSPerformance")
                        .HasColumnType("text");

                    b.Property<string>("Disk2DataPerformance")
                        .HasColumnType("text");

                    b.Property<string>("Disk3DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk4DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk5DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disk6DataType")
                        .HasColumnType("text");

                    b.Property<string>("Disks")
                        .HasColumnType("text");

                    b.Property<string>("EnvironmentTag")
                        .HasColumnType("text");

                    b.Property<string>("Function")
                        .HasColumnType("text");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InfrastructureSupportAzure")
                        .HasColumnType("text");

                    b.Property<string>("InfrastructureSupportServiceLevel")
                        .HasColumnType("text");

                    b.Property<string>("JavaSupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("MonitoringHealthcheckURL")
                        .HasColumnType("text");

                    b.Property<string>("NewHostname")
                        .HasColumnType("text");

                    b.Property<string>("OSSupportIncludingPatching")
                        .HasColumnType("text");

                    b.Property<string>("OperatingSystem")
                        .HasColumnType("text");

                    b.Property<string>("OracleDBASupportRequired")
                        .HasColumnType("text");

                    b.Property<string>("PlanVersion")
                        .HasColumnType("text");

                    b.Property<string>("Port")
                        .HasColumnType("text");

                    b.Property<string>("PrivateIPAddress")
                        .HasColumnType("text");

                    b.Property<string>("Protocol")
                        .HasColumnType("text");

                    b.Property<string>("ProximityGroup")
                        .HasColumnType("text");

                    b.Property<string>("PublicIPAddress")
                        .HasColumnType("text");

                    b.Property<int?>("RamGB")
                        .HasColumnType("integer");

                    b.Property<string>("ResourceGroup")
                        .HasColumnType("text");

                    b.Property<string>("ResponseSLARequirement")
                        .HasColumnType("text");

                    b.Property<string>("SMTPEnabled")
                        .HasColumnType("text");

                    b.Property<string>("SMTPHostname")
                        .HasColumnType("text");

                    b.Property<string>("SMTPSender")
                        .HasColumnType("text");

                    b.Property<string>("Size")
                        .HasColumnType("text");

                    b.Property<string>("Spinner")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subscription")
                        .HasColumnType("text");

                    b.Property<string>("ThreeDExperienceSXILicense")
                        .HasColumnType("text");

                    b.Property<string>("TomEEPortConnector")
                        .HasColumnType("text");

                    b.Property<string>("URL")
                        .HasColumnType("text");

                    b.Property<DateTime?>("VMCreationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("VMDeletionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VirtualNetworkSubnet")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("IG_ResourcesTBL", (string)null);
                });

            modelBuilder.Entity("PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Features.Subscriptions.Models.ConfiguredSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AzureSubscriptionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AzureSubscriptionId")
                        .IsUnique();

                    b.ToTable("IG_ConfiguredSubscriptionsTBL", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8f14e45f-ceea-467e-aded-c0a75a6c1b0a"),
                            AzureSubscriptionId = "5ce689ab-68b4-4c31-8244-22f9f06d84b0",
                            DisplayName = "ac-hybrid-devtest-01"
                        },
                        new
                        {
                            Id = new Guid("c7f1b1d4-4a9b-4e3b-9c9a-6f3b4a8a9b10"),
                            AzureSubscriptionId = "0cbdd8c2-9831-494b-b07b-76952fb13d3a",
                            DisplayName = "ac-hybrid-production-01"
                        },
                        new
                        {
                            Id = new Guid("3e9a4c2b-1d7e-4f6a-8b2c-2a5d9e7f1c44"),
                            AzureSubscriptionId = "a5adb684-975e-4f1f-8769-93bcdf28e936",
                            DisplayName = "ct-private-devtest-01"
                        });
                });

            modelBuilder.Entity("PLMInfrastructureRegisterOrchestratorServiceLayerMSC.Models.Classes.ConfigurationConstantClass", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConfigurationKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ConfigurationValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ConfigurationKey")
                        .IsUnique();

                    b.ToTable("IG_ConfigurationConstantTBL", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d"),
                            ConfigurationKey = "ENVIRONMENT_TAGS",
                            ConfigurationValue = "[\"Production\",\"QA\",\"Testing\",\"Dev1\",\"Dev2\",\"Training\",\"Production Data Migration\",\"Migration Development\",\"DSLS\",\"Non-Production\",\"Secondary Non-Production\",\"21x OOTB\",\"25x OOTB\",\"Unknown\",\"SandBox (Functional)\",\"SandBox (Technical)\",\"Not Assigned\"]",
                            CreatedAt = new DateTime(2026, 10, 6, 0, 0, 0, 0, DateTimeKind.Utc),
                            Notes = "Valid values for Resources.EnvironmentTag, transcribed from the infrastructure register CSV."
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
