@PLMInfrastructureRegisterOrchestratorServiceLayerMSC_HostAddress = http://localhost:5114

GET {{PLMInfrastructureRegisterOrchestratorServiceLayerMSC_HostAddress}}/weatherforecast/
Accept: application/json

###
