// Column order and labels mirror the original spreadsheet exactly — labels
// are the literal legacy header text (per the naming rule: UI-facing text is
// exempt from the project's code-identifier naming conventions).
export interface ResourceColumnDef {
  key: string;
  label: string;
}

export default class ResourceColumnCON {
  public static readonly COLUMNS: ResourceColumnDef[] = [
    { key: 'hostname', label: 'HOSTNAME' },
    { key: 'environmentTag', label: 'ENVIRONMENT (TAG)' },
    { key: 'function', label: 'FUNCTION' },
    { key: 'status', label: 'STATUS' },
    { key: 'dailyBackupTime', label: 'Daily Backup Time (CET)' },
    { key: 'cronJobsTaskScheduler', label: 'Cronjobs / Task scheduler' },
    { key: 'dns', label: 'DNS' },
    { key: 'url', label: 'URL' },
    { key: 'privateIPAddress', label: 'PRIVATE IP ADDRESS' },
    { key: 'category', label: 'TYPE' },
    { key: 'subscription', label: 'SUBSCRIPTION' },
    { key: 'spinner', label: 'Spinner_R2024x_AtlasCopco_Exp29Oct2026' },
    { key: 'autoShutdownEnabled', label: 'Auto Shutdown' },
    { key: 'autoShutdownSchedule', label: 'Auto Shutdown Schedule' },
    { key: 'autoShutdownStartTime', label: 'Auto Shutdown Start Time (CET)' },
    { key: 'autoShutdownEndTime', label: 'Auto Shutdown End Time (CET)' },
    { key: 'resourceGroup', label: 'RESOURCE GROUP' },
    { key: 'location', label: 'LOCATION' },
    { key: 'virtualNetworkSubnet', label: 'VIRTUAL NETWORK/SUBNET' },
    { key: 'proximityGroup', label: 'PROXIMITY GROUP' },
    { key: 'operatingSystem', label: 'OPERATING SYSTEM' },
    { key: 'size', label: 'SIZE' },
    { key: 'cpuCores', label: 'CPU' },
    { key: 'ramGB', label: 'RAM' },
    { key: 'disk1OSPerformance', label: 'DISK 1 (OS) PERFORMANCE' },
    { key: 'disk2DataPerformance', label: 'DISK 2 (DATA) PERFORMANCE' },
    { key: 'disk3DataType', label: 'DISK 3 (DATA) TYPE3' },
    { key: 'disk4DataType', label: 'DISK 4 (DATA) TYPE4' },
    { key: 'disk5DataType', label: 'DISK 5 (DATA) TYPE5' },
    { key: 'disk6DataType', label: 'DISK 6 (DATA) TYPE6' },
    { key: 'databaseInstance', label: 'Database Instance' },
    { key: 'databaseName', label: 'Database Name' },
    { key: 'publicIPAddress', label: 'PUBLIC IP ADDRESS' },
    { key: 'disks', label: 'DISKS' },
    { key: 'planVersion', label: 'PLAN/VERSION' },
    { key: 'backupSchedule', label: 'Backup Schedule' },
    { key: 'backupStatus', label: 'Backup Status' },
    { key: 'infrastructureSupportAzure', label: 'Infrastucture Support (Azure)' },
    { key: 'infrastructureSupportServiceLevel', label: 'Infrastucture Support Service Level (Insight)' },
    { key: 'dbaSupport', label: 'DBA Support' },
    { key: 'dbaSupportServiceLevel', label: 'DBA Support Service Level' },
    { key: 'protocol', label: 'Protocol' },
    { key: 'port', label: 'Port' },
    { key: 'tomEEPortConnector', label: 'TomEE Port Connector' },
    { key: 'smtpEnabled', label: 'SMTP Enabled' },
    { key: 'smtpHostname', label: 'SMTP Hostname' },
    { key: 'smtpSender', label: 'SMTP Sender' },
    { key: 'comment', label: 'Comment' },
    { key: 'oracleDBASupportRequired', label: 'Oracle DBA Support Required' },
    { key: 'javaSupportRequired', label: 'JAVA Support Required' },
    { key: 'apacheSupportRequired', label: 'Apache Support Required' },
    { key: 'backupRequired', label: 'Backup Required' },
    { key: 'osSupportIncludingPatching', label: 'OS Support(inc patching)' },
    { key: 'azureMonitoringSetupRequired', label: 'Azure montioring setup required' },
    { key: 'responseSLARequirement', label: 'Response SLA Requirement' },
    { key: 'atosAgentDeployed', label: 'Atos Agent Deployed' },
    { key: 'threeDExperienceSXILicense', label: '3DExperience SXI License' },
    { key: 'monitoringHealthcheckURL', label: 'Monitoring healthcheck URL' },
    { key: 'vmCreationDate', label: 'VM creation date' },
    { key: 'vmDeletionDate', label: 'VM deletion date' },
    { key: 'newHostname', label: 'New HOSTName' },
  ];
}
